export const FEATURES = {
  shadowing: {
    slug: 'shadowing',
    title: 'Shadowing chuẩn Tokyo',
    eyebrow: 'Kỹ thuật phát âm',
    icon: 'record_voice_over',
    iconWrap: 'bg-[#ffd9e4]/80 text-[#9E2A4B]',
    ctaLabel: 'Trải nghiệm kỹ thuật',
    tryTo: '/lesson-player',
    tryLabel: 'Mở bài shadowing mẫu',
    lead: 'Rèn ngữ điệu, ngắt câu và pitch theo giọng phát thanh viên NHK — phản xạ nói tự nhiên thay vì đọc từng từ.',
    stats: [
      { k: '15 câu', v: 'mỗi phiên luyện' },
      { k: 'NHK', v: 'mẫu ngữ điệu chuẩn' },
      { k: '4 tốc độ', v: 'chậm → bản xứ' },
    ],
    steps: [
      { t: 'Nghe mẫu', d: 'Câu thoại công sở / tin ngắn, waveform và dấu ngắt hơi hiện sẵn.' },
      { t: 'Nói chồng giọng', d: 'Thu âm cùng lúc với bản gốc, giữ nhịp chứ không dịch trong đầu.' },
      { t: 'Đối chiếu pitch', d: 'AI khoanh âm tiết lệch cao độ, đề xuất câu cần ôn lại.' },
    ],
    points: [
      'Bỏ rào ấp úng khi trả lời hội thoại 30 giây',
      'Luyện kaiwa công sở và phỏng vấn Tokutei',
      'Đồng bộ với bài ngữ pháp đang học trên lộ trình',
    ],
    demo: {
      title: 'Phiên mẫu · Bài 15',
      line: '今、電話をかけてもいいですか。',
      note: 'Ngắt hơi sau 「今」、pitch rơi ở 「でんわ」。',
    },
  },
  'ai-scoring': {
    slug: 'ai-scoring',
    title: 'AI Chấm thi & Phát âm',
    eyebrow: 'Haru Sensei AI',
    icon: 'neurology',
    iconWrap: 'bg-[#ffd9dd]/80 text-[#9E2A4B]',
    ctaLabel: 'Xem mô phỏng AI',
    tryTo: '/ai-scoring',
    tryLabel: 'Xem phiếu chấm mẫu',
    lead: 'Thuật toán phân tích Pitch Accent, lỗi âm tiết và dự báo điểm JLPT theo tuần — không chờ đến ngày thi thử.',
    stats: [
      { k: 'Pitch', v: 'từng mora' },
      { k: '±4 điểm', v: 'dự báo mock N3' },
      { k: '< 0.8s', v: 'phản hồi câu viết' },
    ],
    steps: [
      { t: 'Nộp bài', d: 'Ghi âm, viết câu hoặc làm mini-test trong studio.' },
      { t: 'Haru chấm', d: 'Tách lỗi ngữ pháp, từ vựng và phát âm; gắn gợi ý sửa.' },
      { t: 'Lộ trình chỉnh', d: 'Đẩy 5 câu sai vào hàng đợi SRS / shadowing hôm sau.' },
    ],
    points: [
      'Chấm ngữ cảnh, không chỉ đúng/sai trắc nghiệm',
      'Biểu đồ quên lãng gắn với điểm yếu thật',
      'Chia sẻ phiếu cho Sensei 1-kèm-1 trước buổi học',
    ],
    demo: {
      title: 'Phiếu chấm · 経験',
      line: 'Pitch け↘いけん · Mora 3 ổn, rơi muộn 1 nhịp.',
      note: 'Gợi ý: nghe lại mẫu NHK 2 lần rồi thu chồng giọng.',
    },
  },
  srs: {
    slug: 'srs',
    title: '10,000+ Kanji & Flashcard SRS',
    eyebrow: 'Ghi nhớ dài hạn',
    icon: 'auto_stories',
    iconWrap: 'bg-secondary-container/70 text-[#9E2A4B]',
    ctaLabel: 'Thư viện từ vựng',
    tryTo: '/daily-srs',
    tryLabel: 'Mở hàng đợi SRS',
    lead: 'Hán tự gắn hình tượng văn hóa, ôn đúng chu kỳ Ebbinghaus — nhớ gốc từ thay vì nhồi đêm trước kỳ thi.',
    stats: [
      { k: '10,000+', v: 'thẻ N5–N1' },
      { k: 'SM-2', v: 'chu kỳ ngắt quãng' },
      { k: '28 thẻ', v: 'hàng đợi hôm nay' },
    ],
    steps: [
      { t: 'Nạp từ bài học', d: 'Mỗi bài hoàn thành đẩy từ mới + kanji vào sổ.' },
      { t: 'Ôn đúng hạn', d: 'Khẩn cấp / đến hạn / củng cố — 6–15 phút mỗi sáng.' },
      { t: 'Nhớ sâu', d: 'Sai 2 lần thì gắn ví dụ AI và bộ thủ liên tưởng.' },
    ],
    points: [
      'Sổ từ và sổ Kanji đồng bộ một vòng lặp',
      'Không nhồi 200 thẻ/ngày — chỉ đúng cửa sổ quên',
      'Xem chi tiết từng từ: pitch, ví dụ, nét viết',
    ],
    demo: {
      title: 'Thẻ hôm nay · 経験',
      line: 'けいけん · kinh nghiệm · SRS vòng 3',
      note: 'Ôn lại sau 2 ngày. Liên kết Bài 15 ～てもいいです.',
    },
  },
  sensei: {
    slug: 'sensei',
    title: 'Cố vấn chuyên gia 1-on-1',
    eyebrow: 'Sensei tại Nhật',
    icon: 'supervisor_account',
    iconWrap: 'bg-[#b7f481]/50 text-[#366800]',
    ctaLabel: 'Đội ngũ Sensei',
    tryTo: '/consultation',
    tryLabel: 'Xem gói tư vấn',
    lead: 'Sensei người Nhật và giảng viên cao cấp sửa luận, giải đáp 24/7, định hướng nghề và phỏng vấn Tokutei.',
    stats: [
      { k: '45 phút', v: 'mỗi buổi video' },
      { k: '24/7', v: 'hàng đợi văn bản' },
      { k: 'Tokutei', v: 'kèm mock phỏng vấn' },
    ],
    steps: [
      { t: 'Chọn gói', d: 'Video 1-kèm-1, chữa bài viết, hoặc combo lộ trình.' },
      { t: 'Đặt lịch & thanh toán', d: 'Biên lai + phiếu chuẩn bị gửi trước 24 giờ.' },
      { t: 'Vào phòng', d: 'Mở trước 5 phút: chat, agenda, ghi chú sau buổi.' },
    ],
    points: [
      'Hồ sơ Sensei: chuyên môn N3–N1, đánh giá thật',
      'Phiếu trước buổi — không mất 15 phút hỏi lại ngữ cảnh',
      'Ghi chú buổi học vào sổ học viên sau khi rời phòng',
    ],
    demo: {
      title: 'Sensei Sato · Tokyo',
      line: 'Dokkai & ngữ pháp N3–N2 · 4.9 ★ · 312 buổi',
      note: 'Slot mở: Thứ 3 14:00 · Thứ 5 10:00.',
    },
  },
};

export const FEATURE_LIST = Object.values(FEATURES);
